config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :restaurants
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  } 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id         :bigint           not null, primary key
#  location   :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Restaurant < ApplicationRecord

  has_many :users

  has_many :posts, class_name: "Post", foreign_key: "restaurant_id"
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]
  before_action :ensure_user_is_authorized, only: [:show]

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = policy_scope(Restaurant)
    if @restaurants.empty?
      redirect_to root_path, alert: "You are not authorized to view this page."
    end
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
    if !current_user.admin?
      redirect_to root_path, alert: "You are not authorized to view this page."
    end
  end

  # GET /restaurants/1/edit
  def edit
    if !current_user.admin?
      redirect_to root_path, alert: "You are not authorized to view this page."
    end
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :location)
    end

    def ensure_user_is_authorized
      if !RestaurantPolicy.new(current_user, @restaurant).show?
        raise Pundit::NotAuthorizedError, "not allowed"
      end
    end
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant) do |form| %>
  <% if restaurant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <p>
    <strong>Name:</strong>
    <%= restaurant.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= restaurant.location %>
  </p>

</div>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Show this restaurant", @restaurant %> |
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-between align-items-center"">
<h1>Restaurants</h1>
<%= link_to "New restaurant", new_restaurant_path, class: "btn btn-primary" %>
</div>
<div id="restaurants">

  <table class="table">
    <thead>
      <tr>
        <th scope="col">name</th>
        <th scope="col">location</th>
      </tr>
    </thead>
    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <th scope="row"><%= restaurant.name %></th>
          <td><%= restaurant.location %></td>
          <td><%= link_to "Show this restaurant", restaurant %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @restaurant %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">content</th>
      <th scope="col">posted</th>
    </tr>
  </thead>
  <tbody>
<% @restaurant.posts.each do |post|  %>
    <tr>
      <th scope="row"><%= post.content %></th>
      <td><%= post.created_at.strftime("%r %D") %></td>
    </tr>
<% end %>
</tbody>
</table>

<table class="table">
  <thead>
    <tr>
      <th scope="col">employee</th>
      <th scope="col">email</th>
    </tr>
  </thead>
  <tbody>
<% @restaurant.users.each do |user|  %>
    <tr>
      <th scope="row"><%= user.name %></th>
      <th scope="row"><%= user.email %></th>
    </tr>
<% end %>
</tbody>
</table>


<div>
  <%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant) %> |
  <%= link_to "Back to restaurants", restaurants_path %>

  <%= button_to "Destroy this restaurant", @restaurant, method: :delete %>
</div>