config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :restaurants
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  } 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id            :bigint           not null, primary key
#  content       :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  restaurant_id :integer
#  user_id       :integer
#
class Post < ApplicationRecord

  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :ensure_user_is_authorized, only: [:show]

  # GET /posts or /posts.json
  def index
      # @posts = Post.all
      @posts = policy_scope(Post)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if current_user.id != @post.user_id
      redirect_to root_path, alert: "You are not authorized to view this page."
    end
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: "Post was successfully created." }
        format.json { render :index, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :restaurant_id, :content)
    end

    def ensure_user_is_authorized
      if !PostPolicy.new(current_user, @post).show?
        raise Pundit::NotAuthorizedError, "not allowed"
      end
    end
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.number_field :user_id, value: current_user.id, hidden: true %>
  </div>
  
  <div>
    <%= form.number_field :restaurant_id, value: current_user.restaurant_id, hidden: true %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

  <p>
    <strong>Restaurant:</strong>
    <%= post.restaurant_id %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reviews</h1>

<div id="posts">
    


  <table class="table">
  <thead>
    <tr>
      <th scope="col">content</th>
      <th scope="col">posted</th>
    </tr>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <th scope="row"><%= post.content %></th>
      <td><%= post.created_at.strftime("%r %D") %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

<%# <%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New Review</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>